version: '3'

services:

  mongo_crud:
    build:
      context: mongo_crud
      dockerfile: Dockerfile
    command: /bin/sh ./run.sh
    volumes:
      - ./mongo_crud/:/code
    ports:
      - 9001:5000
    networks:
      - backend

  mongo:
    image: mongo
    user: root
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo-express:
      image: mongo-express
      ports:
        - "8000:8081"
      environment:
        ME_CONFIG_BASICAUTH_USERNAME: root
        ME_CONFIG_BASICAUTH_PASSWORD: root
        ME_CONFIG_MONGODB_SERVER: mongo
      networks:
        - backend

networks:
  backend:
    driver: bridge

